### ISSUE TITLE
Cant load

### ISSUE THREAD

**Issue by MarkGorbe** [foroughinia18/xAdmin#1]
this is what i got from the console
```
[    c-resources-core] Resource loading for xAdmin failed:
[    c-resources-core] Could not open resource metadata file - no such file.
```

**Comment by foroughinia18** [comment]
Check that the **fxmanifest.lua** file and other files is in the **xAdmin** folder.

**Comment by MarkGorbe** [comment]
> 
well it is.

the lua file is in:
E:\txData\CFXDefault_096AE5.base\resources\xAdmin\xAdmin

**Comment by foroughinia18** [comment]
**No !**

- [x] True :

> E:\txData\CFXDefault_096AE5.base\resources\xAdmin\fxmanifest.lua and other files

- [ ] False :

> E:\txData\CFXDefault_096AE5.base\resources\xAdmin\xAdmin\fxmanifest.lua and other files

**Comment by foroughinia18** [comment]
_Only use xAdmin folder inside xAdmin folder !_

**Comment by foroughinia18** [comment]
**Only use xAdmin folder inside xAdmin folder !**
> E:\txData\CFXDefault_096AE5.base\resources\xAdmin\ .lua files
